`cake build` works on Windows x64
spawn was causing problem:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
```